name: 'Get Node Version'
description: 'Pulls the Node.js version to be used from the package.json file of a project.'

branding:
  icon: 'search'
  color: 'green'

inputs:
  path: 
    description: 'Specify the path where the package.json file can be found.'
    required: false
    default: './'

runs:
  using: composite
  steps:
    - name: Get Node.js Version
      shell: bash
      run: |
        echo "$(cat ${{ inputs.path }}package.json)" | jq .engines.node | xargs -I {} echo "NodeVersion="{} >> $GITHUB_ENV
    - name: Use Node.js ${{ env.NodeVersion }}
      uses: actions/setup-node@main
      with:
        node-version: ${{ env.NodeVersion }}
        cache: 'npm'
        cache-dependency-path: '${{ inputs.path }}package-lock.json'